---
# tasks file for ssh_key_rotation

  - name: getting ip address
    include: vxen.yml
    when: ansible_virtualization_type == "xen"

  - name: getting ip address
    include: vvirtualbox.yml
    when: ansible_virtualization_type == "virtualbox"

  - name: getting ip address
    include: vkvm.yml
    when: ansible_virtualization_type == "kvm"

  - name: getting ip address
    include: vdocker.yml
    when: ansible_virtualization_type == "docker"

