---
  - name: "adding new public keys"
    authorized_key:
      user: "{{ ansible_user_id }}"
      key: "{{ lookup('file', '{{ old_pubkey_path }}') }}"
      state: present

  - name: "printing ip address"
    command: echo "{{ ansible_default_ipv4.address }}"
    register: host_ip

  - name: ip address
    debug:
      var: host_ip.stdout

  - name: checking if able to ssh with new key or not
    delegate_to: localhost
    shell: ssh -i {{ old_privkey_path }} {{ ansible_user_id }}@{{ ansible_default_ipv4.address }}
    register: output

  - name: "adding new public keys and removing previous key"
    authorized_key:
      user: "{{ ansible_user_id }}"
      key: "{{ lookup('file', '{{ old_pubkey_path }}') }}"
      state: absent
    when: output.rc == 0

